### ISSUE TITLE
Feature request: Serialize participle-tagged structs

### ISSUE THREAD

**Issue by orborde** [alecthomas/participle#100]
[I'm experimenting with using Participle to parse a game's save format](https://github.com/orborde/stellaris_micromanager/blob/master/participle_parser/main.go). It would be really great if Participle could somehow use the struct's tags to _serialize_ the struct to its text format.

At a glance, this looks pretty doable! The only gotcha I've thought of is that the lexer's legal values for a token may not be the same as the legal values for the struct's field - e.g. you have some `string` field tagged `` `@String` ``, but you've set the lexer up with `String = "\"" { "a"..."z" } "\""`.

**Comment by orborde** [comment]
Another corner case:

```
type Expression struct {
	String       *string    `@String`
	Atom         *string    `| @Ident`
}
```

If both `String` and `Atom` are populated, that's a problem! Should probably throw an error in that case.

**Comment by alecthomas** [comment]
There is no deterministic way to do this, unfortunately. The best solution is to implement `fmt.Stringer`, or your own custom marshaller method, and recursively serialise the parsed structure.

**Comment by orborde** [comment]
What's an example of a case that cannot be serialized deterministically?

**Comment by alecthomas** [comment]
The simplest case is this:

```go
String string `@Ident+`
```

Given the input `a b c` this will result in `abc` and no way to reverse it.

Also any tokens that are `Elide()`ed, like comments etc. Finally, any case where you implement the `Capture` or `Parseable` interface.

**Comment by alecthomas** [comment]
That said, as long as the edge cases are documented I think it could be useful. Contributions welcome.

**Comment by alecthomas** [comment]
Thinking about this some more, I don't think this is really possible in a useful way due to the reasons described above, but primarily due to whitespace. Here's an example:

```
a = 300 / (2 + 3)
b = 10
```

All of the whitespace in this generally be lost during parsing, but how do we reconstruct it? There's no way to know where to put spaces or newlines.

I think the current approach of just providing a `String() string` method on each node is probably the best and simplest.

Thanks for the issue though, it's good to think about new ideas.
