### ISSUE TITLE
Floats and Ints

### ISSUE THREAD

**Issue by younisshah** [alecthomas/participle#11]
I've a file which contains the lines like these

`A paid $30.80 for snacks.`
`B paid $70 for house-cleaning.`
`C paid $63.50 for utilities.`

And this is my grammar

```go
type Grammar struct {
	Expenses []*Expense `{ @@ }`
}

type Expense struct {
	Name string `@Ident "paid"`
	Amount *Value `@@`
}

type Value struct {
	Float   *float64 `  "$" @Float {@Ident} "."`
	Integer *int     `| "$" @Int {@Ident} "."`
}
```

While parsing the file, I get `expected ( Float:Float ) not "70"`. 

What's missing? What am I doing wrong?

**Comment by alecthomas** [comment]
Hello! This is because Participle currently does not perform lookahead/backtracking. It's the number one feature I want to implement next.

What's happening is that once you hit `$`, Participle will never backtrack to choose the other path. You'll need to refactor your grammar to look like:

```
type Value struct {
    Float *float64    `"$" (   @Float`
    Integer *int        `         | @Int )`
    Task string        `"for" @Ident { @"-" @Ident } "."`
}
```

(I also added support for capturing the task, including hyphens which `@Ident` does not support)

**Comment by younisshah** [comment]
Thank you for the response.

What would if I had a task with spaces? Something like this:

`X paid $100.10 for phone bill.`

Cheers.

**Comment by alecthomas** [comment]
Whitespace is automatically skipped by the lexer.

**Comment by younisshah** [comment]
Thanks muchly.

Cheers :)

**Comment by alecthomas** [comment]
Oh for the task, sorry!

`@Ident { [ "." ] @Ident }` should work.

**Comment by younisshah** [comment]
This worked for me for the task:

`"for" {@Ident} { @"-" @Ident } "."`
