### ISSUE TITLE
Parse negative numbers

### ISSUE THREAD

**Issue by kashifsoofi** [alecthomas/participle#112]
Hey,
More of a question rather than an issue.

Apologies for naive question, I am trying to implement a simple math parser using this package. I have got it working to parse expressions mentioned below using the examples
1 + 2, 2 + 3

However i am struggling to parse a negative number e.g. `-1 + 3` or find an example to do that.
I have tried it as 

```
type term struct {
	Sign  string `"(-)"?`
	Value *int   `@Int`
}
```

But parsing still fails with unexpected token "-".

Is it not possible to parse a single char/rune without a terminating whitespace?

Thanks in advance
Kashif

**Comment by alecthomas** [comment]
Hi there,

There are a couple of issues. First off, you don't want to have `"(-)"`... anything inside quotes is a literal, so that would attempt to match the exact token `(-)`, which won't exist.

Regarding parsing negative numbers, it very much depends on the lexer you're using. The default `text/scanner` lexer produces separate tokens for `-` and `<int>`. Luckily Participle makes it simple to get around this. If you capture _both_ `-` and `123` into an `int` field, Participle will combine them before parsing the int. eg.

https://play.golang.org/p/b_DQsW_FkAo

```go
package main

import (
	"github.com/alecthomas/participle"
	"github.com/alecthomas/repr"
)

type term struct {
	Value *int   `parser:"@('-'? Int)"`
}

func main() {
	p := participle.MustBuild(&term{})
	t := &term{}
	err := p.ParseString(`-123`, t)
	if err != nil {
		panic(err)
	}
	repr.Println(t)
}
```

Note the `@` is capturing the sub-expression inside `()`.

All the best,
Alec

**Comment by alecthomas** [comment]
BTW if you have further questions feel free to jump in the Gophers slack (linked from the README).

**Comment by kashifsoofi** [comment]
Excellent, thank you very much for your help.

**Comment by kashifsoofi** [comment]
By the way, it was for a Go learning exercise on [Exercism](https://exercism.io), here is my solution

https://exercism.io/my/solutions/d8250aa9b1804450b5332019e036f05a

Would appreciate for your comments.

And please feel free to link or add in examples folder.
