### ISSUE TITLE
why built-in bool cannot be captured with strconv.ParseBool ?

### ISSUE THREAD

**Issue by mechaneg** [alecthomas/participle#114]
and we have to define custom type with custom capturing

**Comment by alecthomas** [comment]
Because `bool` is used to indicate that something matched, which turns out to be much more useful and common in Participle, than wanting to parse `true` or `false` literals. For example, parsing a variable declaration with a trailing optional syntax:

```go
type Var struct {
  Name string `"var" @Ident`
  Type string `":" @Ident`
  Optional bool `@"?"?`
}
```

In practice this gives more useful AST's. If `bool` were to be parsed literally then you'd need to have some alternate type for `Optional` such as `string` or a custom type.

**Comment by mechaneg** [comment]
thanks a lot for explanation
