### ISSUE TITLE
Help with 'expxpected token'

### ISSUE THREAD

**Issue by prasant94** [alecthomas/participle#116]
Hi!

I'm trying to create a parser for this grammar
```
<expr> ::= <cond> | <and_expr> | <or_expr>
<and_expr> ::= "(" <and_expr> ")" | <expr> "&&" <expr>
<or_expr> ::= "(" <or_expr> ")" | <expr> "||" <expr>
<cond> ::= "(" <cond> ")" | <field> <operator> <value>
<field> ::= "fieldA" | "fieldB" | "fieldC"
<operator> ::= "eq" | "ne" | "lt" | "gt"
<value> ::= ("0" |  [1-9] [0-9]*) | [a-z]+
```

When I run this against the input ``(fieldA eq 40) AND (fieldC eq "abc")`` I get `panic: 1:16: unexpected token "AND"`
Here's the code I have so far.

Any idea what I might be missing?

```go
type Expr struct {
	Cond *Cond    `@@`
	And  *AndExpr `| @@`
	Or   *OrExpr  `| @@`
}

type AndExpr struct {
	Unbracket *AndExpr `"(" @@ ")"`
	A         *Expr    `| @@ "AND"`
	B         *Expr    `@@`
}

type OrExpr struct {
	Unbracket *OrExpr `"(" @@ ")"`
	A         *Expr   `| @@ "OR"`
	B         *Expr   `@@`
}

type Cond struct {
	Unbracket *Cond   `"(" @@ ")"`
	Field     *string `| @( "fieldA" | "fieldB" | "fieldC" )`
	Operator  *string `@( "eq" | "ne" | "lt" | "gt"  )`
	Value     *Value  `@@`
}

type Value struct {
	Number *int    `@Int`
	String *string `| @String`
}

func main() {
	parser, err := participle.Build(&Expr{})
	if err != nil {
		panic(err)
	}

	expression := &Expr{}
	
	err = parser.Parse(strings.NewReader(`(fieldA eq 40) AND (fieldC eq "abc")`), expression)

	if err != nil {
		panic(err)
	}
	repr.Println(expression, repr.Indent("  "), repr.OmitEmpty(true))
}
```

**Comment by alecthomas** [comment]
This approach won't work unfortunately. In your example `Expr.Cond` will always match first and according to your grammar that's the end of the expression. That's why you're getting an error.

I recommend one of the following two options for parsing expressions:

1. See the [expr](https://github.com/alecthomas/participle/blob/master/_examples/expr/main.go) example for the simple approach using a recursive descent parser.
2. See [precedenceclimbing](https://github.com/alecthomas/participle/blob/master/_examples/precedenceclimbing/main.go), which is quite a bit more complicated but gives much nicer ASTs.
