### ISSUE TITLE
What does "rule ??? matched, but did not consume any input" mean, and what is the best way to resolve this error?

### ISSUE THREAD

**Issue by colourdelete** [alecthomas/participle#118]
I have the following code snippet:
```go
var lexer = lexer.Must(ebnf.New(`
	Comment = "#" { "\u0000"…"\uffff"-"\n" } .
	SecIdent = "a"…"z" | "A"…"Z" | "0"…"9" | "." .
	Comma = "," .
	Space = "\r\n" | "\n" | "\f" | "\t" | " " .
	Newline = "\r\n" | "\n" | "\f" .
	Dot = "." .
	InText = { "\u0000"…"\uffff"-"'" } .
	SQuote = "'" .
	DQuote = "\"" .
	OParen = "(" .
	CParen = ")" .
	OBrack = "[" .
	CBrack = "]" .
`))
```
```
type Ref struct {
	Ident string `@SecIdent+`
}
```

When running the lexer I get the following error:
```
rule "SecIdent" matched, but did not consume any input
```

How can this rule match without consuming input, or is this a feature in EBNF?

This also happens on other rules such as `InText`, so I think this is a problem with my EBNF.

**Comment by alecthomas** [comment]
For `InText` this is because `{ ... }` consumes _zero_ or more tokens so by itself it will always match, but won't consume any characters, meaning the lexer cannot progress.

FWIW I would highly suggest using the stateful lexer from now on, as the EBNF one is being removed for the upcoming v1 release. Docs on the stateful lexer are here: https://pkg.go.dev/github.com/alecthomas/participle@v0.6.0/lexer/stateful

**Comment by colourdelete** [comment]
Thank you very much. Also, I think the Regexp lexer is also going to be removed? (it says "legacy")

**Comment by colourdelete** [comment]
Also, taking a quick look, I think the stateful lexer is great since it is more like the parser structure of using structs.

**Comment by alecthomas** [comment]
Correct, yes.

**Comment by colourdelete** [comment]
Also, is there a introduction to `lexer/stateful` other than in pkg.go.dev's example: https://pkg.go.dev/github.com/alecthomas/participle@v0.6.0/lexer/stateful#pkg-examples, and in `_examples/stateful`, that cover a  language like JSON or TOML?
