### ISSUE TITLE
check all possibilities before parsing fails

### ISSUE THREAD

**Issue by pbarker** [alecthomas/participle#28]
Hey, love the library but in trying to build a query parser and am hitting an interesting issue. Trying to parse `"key":"value"` as different from `"this phrase"` seems problematic. 

```golang
// Term holds the different possible terms
type Term struct {
	KV            *KV         ` @@ `
	Text          *string     `| @String `
	Subexpression *Expression `| "(" @@ ")"`
}

// KV represents a json kv
type KV struct {
	Key   *Key   `@@`
	Value *Value `@@`
}

// Key holds the possible key types for a kv
type Key struct {
	Ident *string `@Ident ":"`
	Str   *string `| @String ":"`
}

// Value holds the possible values for a kv
type Value struct {
	Bool  *Bool    `@("true"|"false")`
	Str   *string  `| @String`
	Ident *string  `| @Ident`
	Int   *int64   `| @Int`
	Float *float64 `| @Float`
}
```
If in the `Term` struct I put `KV` first, it will fail because it is looking to find the ":" operator when passed a text field. If the I put `Text` first it will fail because it finds the ":" operator on a term kv field. The `Text` and `KV` fields are in `|` statements,  would it be possible to check that all the `|` fail before erring? Or am I missing something with the implementation?

**Comment by alecthomas** [comment]
This is because Participle doesn't perform lookahead; it is effectively an LL(1) parser.

That said there is actually code in there to build lookahead tables to allow LL(k), but it is a bit buggy (eg. the SQL parser completely fails) and I haven't had time to complete the implementation.

You have two options:

1. Try lookahead via the (just added) `participle.UseLookahead()` option (see 35866c3398dd86d16263d1f25f295c0229ffc808 for a test case modelled on your grammar).
2. Manually disambiguate your grammar by factoring out the common prefix.

For option 2, something like below. It's a bit ugly.

```go
type Term struct {
  KVOrText *KVOrText `@@`
  Subexpression *Expression `| "(" @@ ")"`
}

type KVOrText struct {
  Text *string `@String`
  TextValue *Value `[ ":" @@ ]`
  Ident *string `| @Ident`
  IdentValue *Value `":" @@`
}

type Value struct {
  Bool  *bool    `(@"true" | "false")` // BTW, neat trick for bools <-
  Str   *string  `| @String`
  Ident *string  `| @Ident`
  Int   *int64   `| @Int`
  Float *float64 `| @Float`
}
```

**Comment by alecthomas** [comment]
FYI I've fixed a whole bunch of bugs with lookahead, so it should be a lot more useful now.

**Comment by pbarker** [comment]
thank you! plan on giving it a spin next week
