### ISSUE TITLE
Go1.13 golang.org/cl/161199 changes text/scanner error message affecting lexer

### ISSUE THREAD

**Issue by cybrcodr** [alecthomas/participle#50]
Heads up, https://golang.org/cl/161199 updates text/scanner error messages and breaks the assumption in the following code --

https://github.com/alecthomas/participle/blob/master/lexer/text_scanner.go#L56

```sh
$ go test ./...
ok      github.com/alecthomas/participle        0.067s
--- FAIL: TestLexSingleString (0.00s)
    require.go:794:
                Error Trace:    text_scanner_test.go:35
                Error:          Received unexpected error:
                                <source>:1:14: invalid char literal
                Test:           TestLexSingleString
FAIL
FAIL    github.com/alecthomas/participle/lexer  0.033s
ok      github.com/alecthomas/participle/lexer/ebnf     0.045s
ok      github.com/alecthomas/participle/lexer/ebnf/internal    0.019s
```

I can send a PR to update the error message comparison or someone else can come up with a better way of not relying on the error message string.

**Comment by alecthomas** [comment]
Ideally it wouldn't rely on an error message at all, but I couldn't figure out a way to achieve that. In the interim there is already precedent for this kind of change [here](https://github.com/alecthomas/participle/blob/master/lexer/text_scanner_go111_test.go). If you'd like to send through a PR using the same approach I would appreciate it, otherwise I'll get to it at some point.

**Comment by cybrcodr** [comment]
Sent PR for quick fix.  I didn't use build tags for this, but we can if you prefer direct comparison.  Let me know.

**Comment by alecthomas** [comment]
Nah that works for me, thanks!
